version: '3.9'

services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fampay_yt_api
    ports:
      - 6060:6060
    depends_on: 
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fampay_yt
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: